apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: owners.myproject.com
spec:
  group: myproject.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    kind: Owner
    plural: owners
    singular: owner
  subresources:
    status: {}
