apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-service-account-1
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-service-account-2
  namespace: kube-system1
---
apiVersion: myproject.com/v1alpha1
kind: Owner
metadata:
  name: accounts-owner
spec:
  ownedResources:
  - resource: serviceaccounts
    name: sample-service-account-1
    namespace: kube-system
  - resource: serviceaccounts
    name: sample-service-account-2
    namespace: kube-system
